//! Training and evaluation rows. Never published in a snapshot.

use crate::decision::Decision;
use serde::{Deserialize, Serialize};

/// Where a question came from, and therefore how much it can be trusted
/// to resemble something a visitor would actually type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum Origin {
    /// Written by a person.
    Authored,
    /// Generated from a template over aliases and concepts.
    Template,
    /// Generated by a model.
    Teacher,
    /// Generated to be a near miss, on purpose.
    Adversarial,
}

/// Which part of the experiment a row belongs to.
///
/// `Paraphrase` and `OffTopic` are frozen: never trained on, and checked
/// for leakage against the training rows by hash. They are where the value
/// of a model over the deterministic matcher is decided.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum Split {
    /// Trained on.
    Train,
    /// Held out for model selection.
    Validation,
    /// Held out entirely: phrasings containing no alias verbatim.
    Paraphrase,
    /// Held out entirely: questions this corpus cannot answer.
    OffTopic,
}

/// One labelled question.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Question {
    /// What the visitor would type.
    pub text: String,
    /// The decision this question should produce.
    pub decision: Decision,
    /// Where the row came from.
    pub origin: Origin,
    /// Which part of the experiment it belongs to.
    pub split: Split,
}
