//! The collision report: every merge made, and every near miss declined.
//!
//! This document is the only way a person can audit the concept graph, so
//! it names both sides. A merge that should not have happened and a near
//! miss that should have are both corrected in
//! `sources/concept-overrides.ron`, and the report is regenerated.

use crate::normalize::Group;
use crate::overrides::Overrides;
use std::collections::BTreeSet;

/// Two concepts that look related, which the normalizer left alone.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct NearMiss {
    /// What the resemblance is.
    pub kind: &'static str,
    /// The shorter or narrower key.
    pub one: String,
    /// The longer or broader key.
    pub other: String,
}

/// Every resemblance worth a person's attention.
///
/// Two kinds, both mechanical to find and neither safe to act on: a key
/// that is the initials of a multi-word key, and a key that appears as
/// whole words inside a longer key. The first is how an acronym hides; the
/// second is how a narrower idea hides inside a broader one, which is a
/// parent edge rather than a merge.
pub fn near_misses(keys: &BTreeSet<String>) -> Vec<NearMiss> {
    let miss = |kind, one: &str, other: &String| NearMiss {
        kind,
        one: one.to_string(),
        other: other.clone(),
    };
    let mut out = Vec::new();
    for long in keys.iter().filter(|k| k.contains('-')) {
        let words: Vec<&str> = long.split('-').collect();
        let initials: String = words.iter().filter_map(|w| w.chars().next()).collect();
        if keys.contains(&initials) {
            out.push(miss("acronym", &initials, long));
        }
        let shorter = keys.iter().filter(|k| k.len() > 2 && *k != long);
        let inside = shorter.filter(|short| {
            let parts: Vec<&str> = short.split('-').collect();
            parts.len() < words.len() && parts.iter().all(|w| words.contains(w))
        });
        out.extend(inside.map(|short| miss("inside", short, long)));
    }
    out.sort();
    out.dedup();
    out
}

/// The merges the normalizer made: every concept written more than one way.
fn merges(groups: &[Group]) -> String {
    let rows = groups.iter().filter(|g| g.spellings.len() > 1).map(|g| {
        let spellings: Vec<String> = g
            .spellings
            .iter()
            .map(|(text, count)| format!("`{text}` ({count})"))
            .collect();
        format!("| `{}` | {} | {} |\n", g.key, g.label, spellings.join(", "))
    });
    format!(
        "| Concept | Shown as | Spellings found, with how many resources used each |\n|---|---|---|\n{}",
        rows.collect::<String>()
    )
}

/// The near misses, marked with what the override file says about each.
fn misses(near: &[NearMiss], overrides: &Overrides) -> String {
    let rows = near.iter().map(|miss| {
        let merged = overrides.canonical(&miss.one) == miss.other
            || overrides.canonical(&miss.other) == miss.one;
        let parent = overrides
            .parents
            .get(&miss.other)
            .is_some_and(|ps| ps.contains(&miss.one));
        let decision = match (merged, parent) {
            (true, _) => "merged by override",
            (_, true) => "parent by override",
            _ => "left apart",
        };
        format!(
            "| {} | `{}` | `{}` | {decision} |\n",
            miss.kind, miss.one, miss.other
        )
    });
    format!(
        "| Resemblance | One | The other | Decision |\n|---|---|---|---|\n{}",
        rows.collect::<String>()
    )
}

/// What the normalizer does, printed above the tables.
const RULES: &str = "The normalizer unifies spellings only (case, `-`, `_`, `/`, and a plural \
when both forms occur); every other pairing below was left to a person.";

/// Why the near misses are near misses.
const DECLINED: &str = "An acronym and its expansion are not the same string, and a rule that \
merged them would also merge `llm` with `large language monkeys`. A shorter key inside a longer \
one is usually a parent, not a synonym. Both are decided in the override file.";

/// The whole report.
pub fn markdown(groups: &[Group], near: &[NearMiss], overrides: &Overrides) -> String {
    let merged = groups.iter().filter(|g| g.spellings.len() > 1).count();
    let after: BTreeSet<String> = groups.iter().map(|g| overrides.canonical(&g.key)).collect();
    let folded = groups.len() - after.len();
    let head = format!(
        "# Concept collisions\n\nGenerated by `just concepts`. Do not edit: corrections go in\n\
         [`sources/concept-overrides.ron`](../../sources/concept-overrides.ron),\n\
         which is applied after normalization, and then this is regenerated.\n\n\
         {} spelling groups, {merged} of them written more than one way, and {} concepts once\n\
         the override file folded {folded} of them together. {RULES}\n\n",
        groups.len(),
        after.len(),
    );
    let made = format!("## Merges the normalizer made\n\n{}\n", merges(groups));
    let declined = format!(
        "## Near misses it declined\n\n{DECLINED}\n\n{}",
        misses(near, overrides)
    );
    head + &made + &declined
}
