//! The coverage document, written by the run and never by hand.

use crate::{Coverage, Kind};

/// The numbers a reader should see first, and the gate's verdict.
fn table(kinds: &[Kind]) -> String {
    let rows: String = kinds
        .iter()
        .map(|k| {
            format!(
                "| {:?} | {} | {} | {} | {} |\n",
                k.kind,
                k.total,
                k.tagged,
                k.related,
                k.orphans.len()
            )
        })
        .collect();
    let total: usize = kinds.iter().map(|k| k.total).sum();
    let tagged: usize = kinds.iter().map(|k| k.tagged).sum();
    let related: usize = kinds.iter().map(|k| k.related).sum();
    let orphans: usize = kinds.iter().map(|k| k.orphans.len()).sum();
    format!(
        "| Kind | Indexed | Tagged | Related | Unreachable |\n|---|---:|---:|---:|---:|\n\
         {rows}| **All** | **{total}** | **{tagged}** | **{related}** | **{orphans}** |\n"
    )
}

/// What the link check found, and what it cannot speak for.
fn links(coverage: &Coverage) -> String {
    format!(
        "| Result | URLs |\n|---|---:|\n\
         | Resolves (2xx, 3xx) | {} |\n\
         | **Gone (404, 410)** | **{}** |\n\
         | Host refused a robot (401, 403, 405, 429) | {} |\n\
         | No answer (timeout, DNS, TLS) | {} |\n\
         | Never checked | {} |\n\
         | Distinct URLs in the corpus | {} |\n",
        coverage.links.ok,
        coverage.links.missing.len(),
        coverage.links.blocked.len(),
        coverage.links.errored.len(),
        coverage.links.unchecked,
        coverage.links.urls
    )
}

/// The URLs a person should look at, named rather than counted.
fn attention(coverage: &Coverage) -> String {
    let mut rows: Vec<String> = coverage
        .links
        .blocked
        .iter()
        .map(|u| format!("- refused a robot: <{u}>\n"))
        .collect();
    rows.extend(
        coverage
            .links
            .errored
            .iter()
            .map(|u| format!("- no answer: <{u}>\n")),
    );
    if rows.is_empty() {
        return String::new();
    }
    format!("Worth a look, none of them gated:\n\n{}", rows.concat())
}

/// What the two gates mean, printed above the tables.
const GATES: &str = "Two numbers are gated: a resource nothing can reach, and a URL that is \
gone. A resource is reachable when a concept or a relation leads to it; a repository with \
neither -- no topic, no language, nothing linking to it -- is in the corpus and yet unfindable, \
which is the failure this gate exists to catch. A blocked host or an unanswered request is \
reported and not gated: neither is this corpus being wrong.";

/// Why the exclusion count is printed rather than merely applied.
const EXCLUDED: &str = "repositories are excluded by name as not artifacts, with their reasons \
in `sources/repo-exclusions.ron`. They are not counted above, which is why the exclusion is \
written down rather than merely applied.";

/// What an unused concept is, and is not.
const VOCABULARY: &str = "A concept nothing is about is dead weight in the model's output \
vocabulary, not a failure.";

/// The whole document.
pub fn render(coverage: &Coverage, corpus_hash: &str, checked: &str) -> String {
    let failures = coverage.failures();
    let verdict = if failures.is_empty() {
        "**Both gates pass.**".to_string()
    } else {
        format!("**The gates fail.** {}", failures.join("; "))
    };
    let head = format!(
        "# Knowledge coverage\n\nGenerated by `just report`. Do not edit.\n\n\
         Corpus `{corpus_hash}`. Link results last refreshed {checked} and committed in \
         `cache/url-status.json`; `just report` reads that file and makes no network call, \
         `just report-check` refreshes it.\n\n{verdict}\n\n{GATES}\n\n"
    );
    let artifacts = format!(
        "## Artifacts\n\n{}\n{} {EXCLUDED}\n\n",
        table(&coverage.kinds),
        coverage.excluded
    );
    let urls = format!("## Links\n\n{}\n{}\n", links(coverage), attention(coverage));
    let vocabulary = format!(
        "## Vocabulary\n\n{} concepts carry no resource. {VOCABULARY}\n",
        coverage.unused_concepts.len()
    );
    head + &artifacts + &urls + &vocabulary
}
